syntax on
colorscheme default
set nocompatible
set nu
set ruler
set encoding=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set tabstop=4
set softtabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set hlsearch
set incsearch
set showmatch
set undolevels=1000
